### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dmcwhorter** [bobfreitas/hiveunit-mr2#2]
Hi Bob, this is a really neat project!  Would you consider adding clarifying what license this project is available under by [adding a license](https://help.github.com/articles/open-source-licensing/)?

**Comment by bobfreitas** [comment]
@dmcwhorter no worries, this is here to share, do with it as you wish with no restrictions or limitations

**Comment by dmcwhorter** [comment]
@bobfreitas Thank you!
